# -*- coding: utf-8 -*-
"""data_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ZzHoaaQe1a3OIo5zBtJGRCgOP81655I
"""

import seaborn as sns
import pandas as pd

df=pd.read_

import matplotlib.pyplot as plt
import plotly.express as px

tips=sns.load_dataset('tips')
tips

sns.scatterplot(data=tips,x='total_bill',y='tip')

sns.relplot(data=tips,x='total_bill',y='tip',kind='scatter')

sns.scatterplot(data=tips,x='total_bill',y='tip',hue='sex',style='time')

sns.relplot(data=tips,x='total_bill',y='tip',kind='scatter',hue='sex')

sns.scatterplot(data=tips,x='total_bill',y='tip',hue='sex',style='time',size='size')

sns.relplot(data=tips,x='total_bill',y='tip',kind='scatter',hue='sex',style='time',size='size')

gap=px.data.gapminder()
gap

gap=px.data.gapminder()
temp_df=gap[gap['country']=='India']

sns.lineplot(data=temp_df,x='year',y='lifeExp')

sns.relplot(data=temp_df,x='year',y='lifeExp',kind='line')

temp_df=gap[gap['country'].isin(['India','Pakistan','China'])]
temp_df

sns.relplot(kind='line',data=temp_df,x='year',y='lifeExp',hue='country')

sns.lineplot(data=temp_df,x='year',y='lifeExp',hue='country')

temp_df=gap[gap['country'].isin(['India','Brazil','Germany'])]

sns.relplot(kind='line',data=temp_df,x='year',y='lifeExp',hue='country',style='continent')

sns.relplot(kind='scatter',data=tips,x='total_bill',y='tip',hue='sex')

sns.relplot(kind='scatter',data=tips,x='total_bill',y='tip',col='sex')

sns.relplot(kind='scatter',data=tips,x='total_bill',y='tip',row='sex')

sns.relplot(data=tips,x='total_bill',y='tip',col='smoker',row='sex')

sns.relplot(data=gap,x='lifeExp',y='gdpPercap',kind='scatter')

sns.relplot(data=gap,x='lifeExp',y='gdpPercap',kind='scatter',col='year',col_wrap=4)

sns.histplot(data=tips,x='total_bill')

sns.displot(data=tips,x='day',kind='hist')

titanic=sns.load_dataset('titanic')
titanic

sns.displot(data=titanic,x='age',kind='hist',element='step',hue='sex')

sns.displot(data=tips,x='tip,kind='hist',col='sex',element='step)







